### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by nkoren** [jchristman/meteor-application-manager#2]
This sounds great, and potentially like something I'd like to use / contribute to -- but it would be great if there were a demo to check out, prior to trying to build an app with it from scratch. Can you set up a demo site?

**Comment by nkoren** [comment]
Never mind, just found https://github.com/suntzuII/meteor-window-manager.git

**Comment by jchristman** [comment]
@nkoren, meteor-window-manager is actually an older version of this library without layered, multi-application support. What I would suggest doing is checking out https://github.com/jchristman/meteor-os, a library I'm building on top of meteor-application-manager. In that library, you can:

```
cd example
meteor
```

which will run the example. You can register an arbitrary user to login.

The whole idea of MeteorOS is to build a common API for letting apps talk to each other in the browser. There is an example, complex app built in called a "File Browser" that acts like a native OS file browser. That is really the most complex app I have built using this library to date, though I have many planned in my mind. It has drag and drop file upload capabilities as well as a dialog mode that can be used to open a file browser.

I'm open to suggestions and or help developing this library, as I have hope that it could really be something cool. Thanks for the interest!
